// lib/core/theme/app_tokens_lerp.dart

part of 'package:kelime_oyunu/core/theme/app_tokens.dart';

/// Field-by-field [AppTokens.lerp] for animated theme switches.
AppTokens _lerp(AppTokens a, AppTokens b, double t) => AppTokens(
  bgFlat: Color.lerp(a.bgFlat, b.bgFlat, t)!,
  bgHome: LinearGradient.lerp(a.bgHome, b.bgHome, t)!,
  bgGame: LinearGradient.lerp(a.bgGame, b.bgGame, t)!,
  bgMap: LinearGradient.lerp(a.bgMap, b.bgMap, t)!,
  bgWon: LinearGradient.lerp(a.bgWon, b.bgWon, t)!,
  bgLost: LinearGradient.lerp(a.bgLost, b.bgLost, t)!,
  bgDraw: LinearGradient.lerp(a.bgDraw, b.bgDraw, t)!,
  fog: Color.lerp(a.fog, b.fog, t)!,
  surface: Color.lerp(a.surface, b.surface, t)!,
  card: Color.lerp(a.card, b.card, t)!,
  border: Color.lerp(a.border, b.border, t)!,
  board: Color.lerp(a.board, b.board, t)!,
  boardBorder: Color.lerp(a.boardBorder, b.boardBorder, t)!,
  boardShadow: BoxShadow.lerp(a.boardShadow, b.boardShadow, t)!,
  cellLetter: Color.lerp(a.cellLetter, b.cellLetter, t)!,
  cellClue: Color.lerp(a.cellClue, b.cellClue, t)!,
  cellPending: Color.lerp(a.cellPending, b.cellPending, t)!,
  cellWrong: Color.lerp(a.cellWrong, b.cellWrong, t)!,
  clueText: Color.lerp(a.clueText, b.clueText, t)!,
  ink: Color.lerp(a.ink, b.ink, t)!,
  inkBot: Color.lerp(a.inkBot, b.inkBot, t)!,
  inkPending: Color.lerp(a.inkPending, b.inkPending, t)!,
  accent: Color.lerp(a.accent, b.accent, t)!,
  accentInk: Color.lerp(a.accentInk, b.accentInk, t)!,
  arrow: Color.lerp(a.arrow, b.arrow, t)!,
  tile: Color.lerp(a.tile, b.tile, t)!,
  tileInk: Color.lerp(a.tileInk, b.tileInk, t)!,
  tileShadow: Color.lerp(a.tileShadow, b.tileShadow, t)!,
  text: Color.lerp(a.text, b.text, t)!,
  muted: Color.lerp(a.muted, b.muted, t)!,
  faint: Color.lerp(a.faint, b.faint, t)!,
  success: Color.lerp(a.success, b.success, t)!,
  error: Color.lerp(a.error, b.error, t)!,
  bot: Color.lerp(a.bot, b.bot, t)!,
  botInk: Color.lerp(a.botInk, b.botInk, t)!,
  mtn1: Color.lerp(a.mtn1, b.mtn1, t)!,
  mtn2: Color.lerp(a.mtn2, b.mtn2, t)!,
  mtn3: Color.lerp(a.mtn3, b.mtn3, t)!,
  sheet: Color.lerp(a.sheet, b.sheet, t)!,
  sheetText: Color.lerp(a.sheetText, b.sheetText, t)!,
  sheetMuted: Color.lerp(a.sheetMuted, b.sheetMuted, t)!,
  sheetCard: Color.lerp(a.sheetCard, b.sheetCard, t)!,
  solid: Color.lerp(a.solid, b.solid, t)!,
  solidText: Color.lerp(a.solidText, b.solidText, t)!,
  toggleOff: Color.lerp(a.toggleOff, b.toggleOff, t)!,
  knob: Color.lerp(a.knob, b.knob, t)!,
  page: Color.lerp(a.page, b.page, t)!,
  pageText: Color.lerp(a.pageText, b.pageText, t)!,
  pageMuted: Color.lerp(a.pageMuted, b.pageMuted, t)!,
  pageLine: Color.lerp(a.pageLine, b.pageLine, t)!,
  logoMtn: Color.lerp(a.logoMtn, b.logoMtn, t)!,
  logoSun: Color.lerp(a.logoSun, b.logoSun, t)!,
  dim: Color.lerp(a.dim, b.dim, t)!,
);
